spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  application:
    name: visualizer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    # alternative datasource: external mysql database example
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root

  jpa:
    # remove the next line, if you use mysql:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token







